// list of chapters
export const chapters = [
  {
    labelEng: 'Juz 1',
    labelAra: 'آلم',
    pageStart: 2,
    pageEnd: 21,
  },
  {
    labelEng: 'Juz 2',
    labelAra: 'سَيَقُولُ',
    pageStart: 22,
    pageEnd: 41,
  },
  {
    labelEng: 'Juz 3',
    labelAra: 'تِلْكَ ٱلْرُّسُلُ',
    pageStart: 42,
    pageEnd: 61,
  },
  {
    labelEng: 'Juz 4',
    labelAra: 'لَنْ تَنَالُوْ الْبِرَّ',
    pageStart: 62,
    pageEnd: 81,
  },
  {
    labelEng: 'Juz 5',
    labelAra: 'وَٱلْمُحْصَنَاتُ',
    pageStart: 82,
    pageEnd: 101,
  },
  {
    labelEng: 'Juz 6',
    labelAra: 'لَا يُحِبُّ ٱللهُ',
    pageStart: 102,
    pageEnd: 121,
  },
  {
    labelEng: 'Juz 7',
    labelAra: 'وَإِذَا سَمِعُوا',
    pageStart: 122,
    pageEnd: 141,
  },
  {
    labelEng: 'Juz 8',
    labelAra: 'وَلَوْ أَنَّنَا',
    pageStart: 142,
    pageEnd: 161,
  },
  {
    labelEng: 'Juz 9',
    labelAra: 'قَالَ ٱلْمَلَأُ',
    pageStart: 162,
    pageEnd: 181,
  },
  {
    labelEng: 'Juz 10',
    labelAra: 'وَٱعْلَمُواْ',
    pageStart: 182,
    pageEnd: 201,
  },
  {
    labelEng: 'Juz 11',
    labelAra: 'يَعْتَذِرُونَ',
    pageStart: 202,
    pageEnd: 221,
  },
  {
    labelEng: 'Juz 12',
    labelAra: 'وَمَا مِنْ دَآبَّةٍ',
    pageStart: 222,
    pageEnd: 241,
  },
  {
    labelEng: 'Juz 13',
    labelAra: 'وَمَا أُبَرِّئُ',
    pageStart: 242,
    pageEnd: 261,
  },
  {
    labelEng: 'Juz 14',
    labelAra: 'رُبَمَا',
    pageStart: 262,
    pageEnd: 281,
  },
  {
    labelEng: 'Juz 15',
    labelAra: 'سُبْحَانَ ٱلَّذِى',
    pageStart: 282,
    pageEnd: 301,
  },
  {
    labelEng: 'Juz 16',
    labelAra: 'قَالَ أَلَمْ',
    pageStart: 302,
    pageEnd: 321,
  },
  {
    labelEng: 'Juz 17',
    labelAra: 'ٱقْتَرَبَ لِلْنَّاسِ',
    pageStart: 322,
    pageEnd: 341,
  },
  {
    labelEng: 'Juz 18',
    labelAra: 'قَدْ أَفْلَحَ',
    pageStart: 342,
    pageEnd: 361,
  },
  {
    labelEng: 'Juz 19',
    labelAra: 'وَقَالَ ٱلَّذِينَ',
    pageStart: 362,
    pageEnd: 382,
  },
  {
    labelEng: 'Juz 20',
    labelAra: 'أَمَّنْ خَلَقَ',
    pageStart: 382,
    pageEnd: 401,
  },
  {
    labelEng: 'Juz 21',
    labelAra: 'أُتْلُ مَاأُوْحِیَ',
    pageStart: 401,
    pageEnd: 421,
  },
  {
    labelEng: 'Juz 22',
    labelAra: 'وَمَنْ يَّقْنُتْ',
    pageStart: 422,
    pageEnd: 441,
  },
  {
    labelEng: 'Juz 23',
    labelAra: 'وَمَآ لي',
    pageStart: 441,
    pageEnd: 461,
  },
  {
    labelEng: 'Juz 24',
    labelAra: 'فَمَنْ أَظْلَمُ',
    pageStart: 462,
    pageEnd: 481,
  },
  {
    labelEng: 'Juz 25',
    labelAra: 'إِلَيْهِ يُرَدُّ',
    pageStart: 482,
    pageEnd: 502,
  },
  {
    labelEng: 'Juz 26',
    labelAra: 'حم',
    pageStart: 502,
    pageEnd: 521,
  },
  {
    labelEng: 'Juz 27',
    labelAra: 'قَالَ فَمَا خَطْبُكُم',
    pageStart: 522,
    pageEnd: 541,
  },
  {
    labelEng: 'Juz 28',
    labelAra: 'قَدْ سَمِعَ ٱللهُ',
    pageStart: 542,
    pageEnd: 561,
  },
  {
    labelEng: 'Juz 29',
    labelAra: 'تَبَارَكَ ٱلَّذِى',
    pageStart: 562,
    pageEnd: 581,
  },
  {
    labelEng: 'Juz 30',
    labelAra: 'عَمَّ',
    pageStart: 582,
    pageEnd: 604,
  },
];
